import '../models/product.dart';

class MockDataService {
  Future<List<Product>> fetchProducts() async {
    await Future<void>.delayed(const Duration(milliseconds: 350));
    return _products;
  }

  static const List<String> categories = <String>[
    'Tudo',
    'Couvert Simples',
    'Petiscos',
    'Saladas',
    'Lanche 820',
    'Combinados Frios',
    'Porcoes Quentes',
    'Adicionais',
    'Pratos',
  ];

  static const String _logo = 'assets/images/logo.jpg';
  static const String _menu = 'assets/images/cardapio.jpg';
  static const String _adicionais = 'assets/images/produtos/adicionais.jpg';

  static final List<Product> _products = <Product>[
    Product(
      id: 'cv-1',
      name: 'Amendoim Tradicional',
      description: 'Couvert simples de amendoim com pele.',
      price: 17.40,
      image: _menu,
      category: 'Couvert Simples',
      ingredients: <String>['Amendoim torrado', 'Sal'],
    ),
    Product(
      id: 'cv-2',
      name: 'Azeitonas Verdes',
      description: 'Porcao fria para acompanhar o chope.',
      price: 17.40,
      image: _menu,
      category: 'Couvert Simples',
      ingredients: <String>['Azeitonas verdes', 'Temperos da casa'],
    ),
    Product(
      id: 'cv-3',
      name: 'Cenoura Palito',
      description: 'Legumes em tiras, ideal para petiscar.',
      price: 17.40,
      image: _menu,
      category: 'Couvert Simples',
      ingredients: <String>['Cenoura fresca', 'Tempero leve'],
    ),
    Product(
      id: 'cv-4',
      name: 'Mussarela',
      description: 'Mussarela em porcao fria.',
      price: 17.40,
      image: _logo,
      category: 'Couvert Simples',
      ingredients: <String>['Mussarela fatiada'],
    ),
    Product(
      id: 'pt-1',
      name: 'Fritas com Queijo',
      description: 'Petisco classico para dividir.',
      price: 39.90,
      image: _logo,
      category: 'Petiscos',
      ingredients: <String>['Batata frita', 'Queijo derretido', 'Sal'],
    ),
    Product(
      id: 'pt-2',
      name: 'Fritas com Bacon',
      description: 'Batata crocante coberta com bacon.',
      price: 39.90,
      image: _logo,
      category: 'Petiscos',
      ingredients: <String>['Batata frita', 'Bacon crocante', 'Sal'],
    ),
    Product(
      id: 'pt-3',
      name: 'Fritas com Cheddar e bacon',
      description: 'Batata frita com molho cheddar cremoso e com bacon crocante.',
      price: 39.90,
      image: 'assets/images/produtos/fritas_bacon_cheddar.jpg', 
      category: 'Petiscos',
      ingredients: <String>['Batata frita', 'Cheddar cremoso','Bacon'],
    ),
    Product(
      id: 'pt-4',
      name: 'Fritas com Queijo e Bacon',
      description: 'Batata frita com queijo e bacon.',
      price: 44.90,
      image: 'assets/images/produtos/fritas_bacon_queijo.jpg',
      category: 'Petiscos',
      ingredients: <String>['Batata frita', 'Queijo', 'Bacon'],
    ),
    Product(
      id: 'pt-5',
      name: 'Mandioca Frita',
      description: 'Mandioca dourada e sequinha.',
      price: 29.90,
      image: _menu,
      category: 'Petiscos',
      ingredients: <String>['Mandioca', 'Sal', 'Tempero da casa'],
    ),
    Product(
      id: 'pt-6',
      name: 'Torresmo',
      description: 'Torresmo crocante em porcao.',
      price: 36.90,
      image: 'assets/images/produtos/torresmo.jpg',
      category: 'Petiscos',
      ingredients: <String>['Barriga suina', 'Sal', 'Limpeza e fritura lenta'],
    ),
    Product(
      id: 'pt-7',
      name: 'Kibe Frito com Molho Tartaro',
      description: 'Unidades de kibe crocante com molho.',
      price: 36.90,
      image: _menu,
      category: 'Petiscos',
      ingredients: <String>[
        'Massa de kibe',
        'Carne moida',
        'Temperos arabes',
        'Molho tartaro',
      ],
    ),
    Product(
      id: 'pt-8',
      name: 'Kibe Recheado com Catupiry',
      description: 'Kibe recheado com Catupiry e frito na hora.',
      price: 47.90,
      image: _menu,
      category: 'Petiscos',
      ingredients: <String>[
        'Massa de kibe',
        'Carne moida',
        'Catupiry',
        'Temperos',
      ],
    ),
    Product(
      id: 'pt-9',
      name: 'Bolinho de Costela',
      description: 'Porcao de bolinhos artesanais.',
      price: 37.90,
      image: 'assets/images/produtos/fritas_bacon_queijo.jpg',
      category: 'Petiscos',
      ingredients: <String>['Costela', 'Massa temperada', 'Empanado'],
    ),
    Product(
      id: 'pt-10',
      name: 'Bolinho de Bacalhau',
      description: 'Tradicional bolinho crocante.',
      price: 37.90,
      image: 'assets/images/produtos/fritas_bacon_queijo.jpg',
      category: 'Petiscos',
      ingredients: <String>['Bacalhau', 'Batata', 'Temperos', 'Empanado'],
    ),
    Product(
      id: 'pt-11',
      name: 'Bolinho de Tilapia com Queijo',
      description: 'Bolinho de peixe recheado com queijo.',
      price: 37.90,
      image: 'assets/images/produtos/fritas_bacon_queijo.jpg',
      category: 'Petiscos',
      ingredients: <String>['Tilapia', 'Queijo', 'Massa da casa', 'Empanado'],
    ),
    Product(
      id: 'pt-12',
      name: 'Moela de Frango',
      description: 'Porcao temperada e cozida.',
      price: 35.90,
      image: _menu,
      category: 'Petiscos',
      ingredients: <String>['Moela', 'Tomate', 'Cebola', 'Tempero da casa'],
    ),
    Product(
      id: 'pt-13',
      name: 'Pastelzinho de Carne (25 un.)',
      description: 'Mini pasteis para compartilhar.',
      price: 35.00,
      image: 'assets/images/produtos/fritas_bacon_queijo.jpg',
      category: 'Petiscos',
      ingredients: <String>['Massa de pastel', 'Carne moida', 'Temperos'],
    ),
    Product(
      id: 'pt-14',
      name: 'Pastelzinho de Queijo (25 un.)',
      description: 'Mini pasteis recheados com queijo.',
      price: 35.00,
      image: 'assets/images/produtos/fritas_bacon_queijo.jpg',
      category: 'Petiscos',
      ingredients: <String>['Massa de pastel', 'Mussarela'],
    ),
     Product(
      id: 'pt-15',
      name: 'Fritas',
      description: 'Batata Frita .',
      price: 29.90,
      image: 'assets/images/produtos/fritas.jpg', 
      category: 'Petiscos',
      ingredients: <String>['Batata Frita'],
    ),
    Product(
      id: 'sd-1',
      name: 'Salada de Palmito 300g',
      description: 'Salada fresca com folhas e legumes.',
      price: 43.40,
      image: 'assets/images/produtos/salada_palmito.jpg',
      category: 'Saladas',
      ingredients: <String>['Palmito', 'Alface', 'Tomate', 'Cebola'],
    ),
    Product(
      id: 'sd-2',
      name: 'Tomate e Cebola 280g',
      description: 'Salada classica de acompanhamento.',
      price: 19.40,
      image: _menu,
      category: 'Saladas',
      ingredients: <String>['Tomate', 'Cebola', 'Azeite', 'Sal'],
    ),
    Product(
      id: 'ln-1',
      name: 'Lanche 820',
      description: 'Sanduiche artesanal completo da casa.',
      price: 31.40,
      image: _logo,
      category: 'Lanche 820',
      ingredients: <String>[
        'Pao de hamburguer',
        'Hamburguer artesanal',
        'Queijo prato ou cheddar',
        'Alface',
        'Tomate',
        'Molho da casa',
      ],
    ),
    Product(
      id: 'ln-2',
      name: 'Hamburguer 820 no prato',
      description: 'Hamburguer no prato da casa.',
      price: 31.40,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Lanche 820',
      ingredients: <String>[
        'Hamburguer artesanal',
        'Queijo prato ou cheddar',
        'Bacon',
        'Salada',
      ],
    ),
    Product(
      id: 'cf-1',
      name: 'Combinado Frio Misto (500g)',
      description: 'Tacao frio para petiscar e compartilhar.',
      price: 52.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Combinados Frios',
      ingredients: <String>[
        'Queijo',
        'Salame',
        'Carne',
        'Cenoura',
        'Presunto',
        'Mussarela',
        'Ovos',
        'Condimentos',
      ],
    ),
    Product(
      id: 'cf-2',
      name: 'Carpaccio de Carne e Alcaparras',
      description: 'Laminas finas de carne com toque de alcaparras.',
      price: 46.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Combinados Frios',
      ingredients: <String>[
        'Carne bovina fatiada',
        'Alcaparras',
        'Azeite',
        'Tempero da casa',
      ],
    ),
    Product(
      id: 'pq-1',
      name: 'Picanha no Palito com Mandioca',
      description: 'Acompanha vinagrete e pao.',
      price: 89.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>['Picanha', 'Mandioca', 'Vinagrete', 'Pao'],
    ),
    Product(
      id: 'pq-2',
      name: 'File Mignon no Palito Acebolado',
      description: 'Acompanha pao.',
      price: 65.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>['File mignon', 'Cebola', 'Tempero da casa', 'Pao'],
    ),
    Product(
      id: 'pq-3',
      name: 'Maminha ao Molho Madeira',
      description: 'Com champignon, cebola, tomate e pao.',
      price: 57.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>[
        'Maminha',
        'Molho madeira',
        'Champignon',
        'Cebola',
        'Tomate',
        'Pao',
      ],
    ),
    Product(
      id: 'pq-4',
      name: 'Maminha no Palito Salteada',
      description: 'Com cebola, mandioca e pao.',
      price: 55.90,
      image:'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>['Maminha', 'Cebola', 'Mandioca', 'Pao'],
    ),
    Product(
      id: 'pq-5',
      name: 'Fraldinha no Palito',
      description: 'Com legumes, mandioca e pao.',
      price: 55.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>['Fraldinha', 'Legumes', 'Mandioca', 'Pao'],
    ),
    Product(
      id: 'pq-6',
      name: 'Carne Seca Acebolada',
      description: 'Acompanha mandioca e pao.',
      price: 49.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>['Carne seca', 'Cebola roxa', 'Mandioca', 'Pao'],
    ),
    Product(
      id: 'pq-7',
      name: 'Pernil na Cachaca no Palito',
      description: 'Com molho, cebola roxa e pao.',
      price: 49.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>[
        'Pernil',
        'Reducao de cachaca',
        'Molho da casa',
        'Cebola roxa',
        'Pao',
      ],
    ),
    Product(
      id: 'pq-8',
      name: 'Tirinhas de Tilapia com Molho Tartaro',
      description: 'Peixe em tiras empanadas.',
      price: 49.95,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>['Tilapia', 'Empanado', 'Molho tartaro'],
    ),
    Product(
      id: 'pq-9',
      name: 'Croc de (Tilapia Crocante com Queijo)',
      description: 'Tilapia crocante com recheio de queijo.',
      price: 49.95,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>['Lombo de tilapia', 'Queijo', 'Empanado crocante'],
    ),
    Product(
      id: 'pq-10',
      name: 'Raquete de Frango',
      description: 'Acompanha tomate com cebola.',
      price: 39.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>['Raquete de frango', 'Tomate', 'Cebola'],
    ),
    Product(
      id: 'pq-11',
      name: 'Tulipa de Frango',
      description: 'Acompanha tomate com cebola.',
      price: 39.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>['Tulipa de frango', 'Tomate', 'Cebola'],
    ),
    Product(
      id: 'pq-12',
      name: 'Frango a Passarinho',
      description: 'Porcao classica com tomate e cebola.',
      price: 39.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>['Frango a passarinho', 'Tomate', 'Cebola'],
    ),
    Product(
      id: 'pq-13',
      name: 'File de Frango com Catupiry Acebolado',
      description: 'File acebolado no ponto da casa.',
      price: 34.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>['File de frango', 'Catupiry', 'Cebola', 'Tempero da casa'],
    ),
    Product(
      id: 'pq-14',
      name: 'Linguica de Pernil com Mandioca',
      description: 'Acompanha vinagrete e pao.',
      price: 34.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>['Linguica de pernil', 'Mandioca', 'Vinagrete', 'Pao'],
    ),
    Product(
      id: 'pq-15',
      name: 'Calabresa Acebolada com Tomate',
      description: 'Acompanha pao.',
      price: 34.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Porcoes Quentes',
      ingredients: <String>['Calabresa', 'Cebola', 'Tomate', 'Pao'],
    ),
    Product(
      id: 'ad-1',
      name: 'Adicional de Bacon',
      description: 'Porcao adicional de bacon.',
      price: 9.95,
      image: _adicionais,
      category: 'Adicionais',
      ingredients: <String>['Bacon crocante'],
    ),
    Product(
      id: 'ad-2',
      name: 'Adicional de Catupiry',
      description: 'Porcao adicional de catupiry.',
      price: 9.95,
      image: _adicionais,
      category: 'Adicionais',
      ingredients: <String>['Catupiry'],
    ),
    Product(
      id: 'ad-3',
      name: 'Adicional de Mussarela',
      description: 'Porcao adicional de mussarela.',
      price: 9.95,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Adicionais',
      ingredients: <String>['Mussarela'],
    ),
    Product(
      id: 'ad-4',
      name: 'Adicional de Cheddar',
      description: 'Porcao adicional de cheddar.',
      price: 9.95,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Adicionais',
      ingredients: <String>['Cheddar cremoso'],
    ),
    Product(
      id: 'ad-5',
      name: 'Guarnicao de Arroz',
      description: 'Porcao extra de arroz.',
      price: 9.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Adicionais',
      ingredients: <String>['Arroz branco', 'Alho', 'Sal'],
    ),
    Product(
      id: 'pr-1',
      name: 'Strogonoff de Frango',
      description: 'Arroz, frango e batata palha.',
      price: 51.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Pratos',
      ingredients: <String>['Frango', 'Creme de leite', 'Molho', 'Arroz', 'Batata palha'],
    ),
    Product(
      id: 'pr-2',
      name: 'Strogonoff de Carne',
      description: 'Arroz e batata palha.',
      price: 51.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Pratos',
      ingredients: <String>['Carne', 'Creme de leite', 'Molho', 'Arroz', 'Batata palha'],
    ),
    Product(
      id: 'pr-3',
      name: 'File de Frango a Parmegiana',
      description: 'Com arroz e fritas.',
      price: 61.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Pratos',
      ingredients: <String>[
        'File de frango',
        'Molho de tomate',
        'Queijo',
        'Arroz',
        'Batata frita',
      ],
    ),
    Product(
      id: 'pr-4',
      name: 'File de Tilapia a Parmegiana',
      description: 'Com arroz e fritas.',
      price: 64.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Pratos',
      ingredients: <String>[
        'File de tilapia',
        'Molho de tomate',
        'Queijo',
        'Arroz',
        'Batata frita',
      ],
    ),
    Product(
      id: 'pr-5',
      name: 'File Mignon Bovino a Parmegiana',
      description: 'Com arroz e fritas.',
      price: 64.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Pratos',
      ingredients: <String>[
        'File mignon bovino',
        'Molho de tomate',
        'Queijo',
        'Arroz',
        'Batata frita',
      ],
    ),
    Product(
      id: 'pr-6',
      name: 'Picanha Fatiada',
      description: 'Com mandioca ou fritas e vinagrete.',
      price: 89.90,
      image: 'assets/images/produtos/fritas.jpg',
      category: 'Pratos',
      ingredients: <String>['Picanha fatiada', 'Mandioca ou fritas', 'Vinagrete'],
    ),
  ];
}
