// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz_pY9mUvhgfJUjrjQYjP7win7eaqcmQk',
    appId: '1:984856277343:web:92d05df748de71873786ea',
    messagingSenderId: '984856277343',
    projectId: 'choperia-820-app-4f675',
    authDomain: 'choperia-820-app-4f675.firebaseapp.com',
    storageBucket: 'choperia-820-app-4f675.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ZN_dk8rSj6_ySqJ7alEoEYvx6YXffew',
    appId: '1:984856277343:android:e6bcf2810acdd6933786ea',
    messagingSenderId: '984856277343',
    projectId: 'choperia-820-app-4f675',
    storageBucket: 'choperia-820-app-4f675.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx5y7e9dvyIrdIhmCRewIyZ37nwk42QK0',
    appId: '1:984856277343:ios:3ec984337489248c3786ea',
    messagingSenderId: '984856277343',
    projectId: 'choperia-820-app-4f675',
    storageBucket: 'choperia-820-app-4f675.firebasestorage.app',
    iosBundleId: 'com.example.choperia820app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx5y7e9dvyIrdIhmCRewIyZ37nwk42QK0',
    appId: '1:984856277343:ios:3ec984337489248c3786ea',
    messagingSenderId: '984856277343',
    projectId: 'choperia-820-app-4f675',
    storageBucket: 'choperia-820-app-4f675.firebasestorage.app',
    iosBundleId: 'com.example.choperia820app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz_pY9mUvhgfJUjrjQYjP7win7eaqcmQk',
    appId: '1:984856277343:web:1af7461dfb4395663786ea',
    messagingSenderId: '984856277343',
    projectId: 'choperia-820-app-4f675',
    authDomain: 'choperia-820-app-4f675.firebaseapp.com',
    storageBucket: 'choperia-820-app-4f675.firebasestorage.app',
  );

}